Adiciona tarefa extra
turing-usp/Trainee-RL-2021 pull request #6
Opened 2021-11-26 01:30 UTC by Berbardo

2021-11-26 16:03 UTC, fernandokm requested changes

2021-11-26 16:03 UTC, fernandokm commented on README.md
> +Para treinar seu próprio agente, basta apenas rodar [este Jupyter Notebook](https://colab.research.google.com/drive/1hzRhoJ8UuBs-rK8DID3l85k-8Z8MxqXL#forceEdit=true&sandboxMode=true) em seu Google Co
```suggestion
Para treinar seu próprio agente, basta rodar [este Jupyter Notebook](https://colab.research.google.com/drive/1hzRhoJ8UuBs-rK8DID3l85k-8Z8MxqXL#forceEdit=true&sandboxMode=true) em seu Google Colaboratory. Recomendamos, antes de começar, que você converse com algum dos veteranos da área, copie o notebook para seu drive e edite os hiperparâmetros conforme necessário!
```

2021-11-26 16:03 UTC, fernandokm commented on README.md
> +**DISCLAMER:** Os agentes de vôlei demorarão muitas horas (3+) para serem treinados e nem sempre superarão a IA já programada no próprio jogo, então não se desanime caso não esteja obtendo resultados
```suggestion
**DISCLAMER:** Os agentes de vôlei demorarão muitas horas (3+) para serem treinados e nem sempre superarão a IA já programada no próprio jogo, então não se desanime caso não esteja obtendo resultados rapidamente! Lembrando que esta é uma tarefa **100% opcional**.
```
To bem ambivalente em relação a essa sugestão.

2021-11-30 02:25 UTC, fernandokm approved these changes

2021-11-30 09:21 UTC, fernandokm commented
@Berbardo O notebook da tarefa extra vai entrar no repo, ao invés de ficar no drive?

2021-11-30 20:18 UTC, Berbardo commented
> @Berbardo O notebook da tarefa extra vai entrar no repo, ao invés de ficar no drive?

n sei, oq vc acha melhor? se colocar no repo eles ainda conseguem salvar modelo no drive deles e copiar o notebook?

2021-11-30 22:54 UTC, fernandokm commented
> > @Berbardo O notebook da tarefa extra vai entrar no repo, ao invés de ficar no drive?
> 
> n sei, oq vc acha melhor?

Eu prefiro deixar no github pq daí fica salvo com o resto das coisas.

> se colocar no repo eles ainda conseguem salvar modelo no drive deles e copiar o notebook?

Sim, o link do colab/gh deixa salvar no drive (igual o do playground), e a api do drive funciona da msm forma. Só precisaria atualizar o link do colab pra pegar o nb do github ao invés do drive.

2021-12-05 12:45 UTC, fernandokm commented
@Berbardo Esses merges foram porque você tinha esquecido de dar pull antes de commitar? Se sim, favor limpar o histórico (nesse caso os merges são inúteis) com:

```
git reset --soft HEAD~3 &&
git commit
git push --force
```

2021-12-06 08:07 UTC, fernandokm approved these changes

2021-12-06 18:35 UTC, merged